version: '3.8'

services:
  app:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: finance_radar_api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    container_name: finance_radar_webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
